### ISSUE TITLE
Tamaño de imagen incorrecto en lista de amigos. Se ve demasiado grande

### ISSUE THREAD

**Issue by opueyociutad** [UNIZAR-30226-2021-01/risk_webapp#55]
![imagen](https://user-images.githubusercontent.com/24795695/115229899-e26a4d00-a113-11eb-9e03-adb4b10b4a66.png)

**Comment by opueyociutad** [comment]
![imagen](https://user-images.githubusercontent.com/24795695/115230527-c9ae6700-a114-11eb-8e9e-86b63d1e53a7.png)

**Comment by alecron** [comment]
arreglado, si se produce algún fallo igual añadir al CSS un width: 3rem; aproximadamente
